version: "3.9"

services:
  # FastAPI Application 
  # ai-screening-api:
  #   build: .
  #   container_name: ai-screening-api
  #   restart: always
  #   depends_on:
  #     - redis-stack
  #     - postgres
  #   env_file: .env
  #   ports:
  #     - "8004:8004"
  #   volumes:
  #     - .:/code
  #     - ./data/uploads:/code/data/uploads
  #   command: >
  #     bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload"
  #   networks:
  #     - ai_net

  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: ai-screening-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.admin
      POSTGRES_DB: ai_screening
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ai_net

  # Redis Stack (Vector + Insight)
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--appendonly yes --save 60 1
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
