version: "3.8"

services:
  ai-screening-api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    container_name: ai-screening-api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis-stack:
        condition: service_healthy
    env_file: .env
    environment:
      # Override untuk runtime di Docker (jangan pakai localhost)
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ai_screening
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.admin
      DATABASE_URL: postgresql+psycopg2://admin:admin.admin@postgres:5432/ai_screening

      REDIS_URL: redis://redis-stack:6379/0

      SERVER_HOST: 0.0.0.0
      SERVER_PORT: "8004"
    ports:
      - "8004:8004"
    volumes:
      - .:/app
      - ./data/uploads:/app/data/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8004/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - ai_net

  postgres:
    image: postgres:16
    container_name: ai-screening-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.admin
      POSTGRES_DB: ai_screening
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ai_screening -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - ai_net

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--appendonly yes --save 60 1
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
