version: "3.9"

services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    network_mode: host
    environment:
      NGROK_AUTHTOKEN: 2sFjABwueaxWW8tsRI0F3EtygMD_6KGbnvfo5AqPB8p7U2sY6
    command: >
      http --log stdout --log-format logfmt --region ap host.docker.internal:8004
